#pragma once

// Common
#define MENU_PANEL_NAME             L"Fixed-Width Data Visualizer"
#define MENU_SHOW_PANEL             L"Show FWData&Viz Panel"
#define MENU_CARET_FRAMED           L"Fr&amed Current Line"
#define MENU_CONFIG_FILE_TYPES      L"Configure &File Types"
#define MENU_CONFIG_THEMES          L"Configure Color &Themes"
#define MENU_FIELD_JUMP             L"&Jump to Field"
#define MENU_FIELD_COPY             L"Field &Copy"
#define MENU_FIELD_PASTE            L"Field &Paste"
#define MENU_FIELD_LEFT             L"Move to &Left edge of the Field"
#define MENU_FIELD_RIGHT            L"Move to &Right edge of the Field"
#define MENU_DATA_EXTRACTION        L"&Data Extraction"
#define MENU_DEMO_SINGLE_REC_FILES  L"Sample &Single-Record-Type Files"
#define MENU_DEMO_MULTI_REC_FILES   L"Sample &Multiple-Record-Type Files"
#define MENU_DEMO_MULTI_LINE_FILES  L"Sample M&ultiple-Line Record Files"
#define MENU_ABOUT                  L"A&bout"


// Fixed Width Data Visualizer Panel
#define VIZ_PANEL_FILETYPE_LABEL    L"&File Type:"
#define VIZ_PANEL_THEME_LABEL       L"&Visualizer Theme:"
#define VIZ_PANEL_CLEAR_BUTTON      L"Cle&ar"
#define VIZ_PANEL_CLOSE             L"C&lose"
#define VIZ_PANEL_AUTO_DETECT_FT    L"Auto-detect File Type"
#define VIZ_PANEL_MCBS_OVERRIDE     L"Multi-Byte Chars"
#define VIZ_PANEL_CARET_FRAMED      L"Framed Current Line"
#define VIZ_PANEL_FIELD_COPY_TRIM   L"Trim Field Copy"
#define VIZ_PANEL_FIELD_LABEL       L"Cursor Position Data"
#define VIZ_PANEL_JUMP_FIELD_BTN    L"&Jump to Field"
#define VIZ_PANEL_EXTRACT_DATA_BTN  L"&Data Extraction"
#define VIZ_PANEL_FIELD_COPY_BTN    L"Field &Copy"
#define VIZ_PANEL_FIELD_PASTE_BTN   L"Field &Paste"
#define VIZ_PANEL_PASTE_LEFT_LABEL  L"Left-aligned"
#define VIZ_PANEL_PASTE_RIGHT_LABEL L"Right-aligned"
#define VIZ_PANEL_PASTE_RPAD_LABEL  L"&RPAD:"
#define VIZ_PANEL_PASTE_LPAD_LABEL  L":&LPAD"
#define VIZ_PANEL_INFO_TIP          L"View Readme Online"
#define VIZ_PANEL_FILE_SAMPLES_TIP  L"View Sample Files"
#define VIZ_PANEL_FILE_CONFIG_TIP   L"Open File Type Metadata Editor"
#define VIZ_PANEL_THEME_CONFIG_TIP  L"Open Visualizer Theme Editor"
#define VIZ_PANEL_FIELD_TRIM_TIP    L"When copying a field, trim the padding character on the right or left\r\ndepending on which field edge is closer to the cursor position."
#define VIZ_PANEL_FIELD_LEFT_TIP    L"Move cursor to the Left edge of the current field"
#define VIZ_PANEL_FIELD_RIGHT_TIP   L"Move cursor to the Right edge of the current field"
#define VIZ_PANEL_FIELD_LPAD_TIP    L"Paste clipboard data into the current field,\r\naligned to the left edge with padding on the right."
#define VIZ_PANEL_FIELD_RPAD_TIP    L"Paste clipboard data into the current field,\r\naligned to the right edge with padding on the left."
#define VIZ_PANEL_JUMP_FIELD_TITLE  L"Jump to Field"
#define VIZ_PANEL_JUMP_CHANGED_DOC  L"The currently active document is of a different File Type.\r\n\r\nUnable to jump to the specified field."
#define VIZ_PANEL_JUMP_CHANGED_REC  L"Caret has moved to a different Record Type.\r\n\r\nUnable to jump to the specified field."
#define VIZ_PANEL_DARKMODE_CHANGED  L"Please restart Notepad++ to refresh the FWDataViz plugin panel and dialogs with the changed Darkmode settings."

#define CUR_POS_DATA_BLANK_LINE     L"<Blank Line>"
#define CUR_POS_DATA_UNKOWN_REC     L"<Unknown Record Type>"
#define CUR_POS_DATA_REC_END        L"<Record End>"
#define CUR_POS_DATA_REC_TERM       L"<Record Terminator>"
#define CUR_POS_DATA_REC_TYPE       L"  Record Type: "
#define CUR_POS_DATA_REC_LENGTH     L"Record Length: "
#define CUR_POS_DATA_CURR_DEFINED   L" [Current/Defined]"
#define CUR_POS_DATA_OVERFLOW       L"    Overflow!"
#define CUR_POS_DATA_FIELD_LABEL    L"  Field Label: "
#define CUR_POS_DATA_FIELD_NUM      L"Field #"
#define CUR_POS_DATA_FIELD_START    L"  Field Start: "
#define CUR_POS_DATA_FIELD_WIDTH    L"  Field Width: "
#define CUR_POS_DATA_FIELD_COL      L" Field Column: "
#define CUR_POS_DATA_ANSI_BYTE      L"    ANSI Byte: "
#define CUR_POS_DATA_UTF8_BYTES     L"  UTF-8 Bytes: "


// About Dialog
#define ABOUT_DIALOG_TITLE          L"About"
#define ABOUT_PLUGIN_NAME           L"Fixed Width Data Visualizer Plugin for Notepad++"
#define ABOUT_BTN_LABEL_OK          L"&OK"


// Configuration Dialog
#define FWVIZ_DIALOG_TITLE          L"File Type Metadata Editor"
#define FWVIZ_DEF_FILE_GROUP_BOX    L"File Type"
#define FWVIZ_DEF_FILE_MOVE_DOWN    L"Move down the selected File Type"
#define FWVIZ_DEF_FILE_MOVE_UP      L"Move up the selected File Type"
#define FWVIZ_DEF_FILE_DESC_LABEL   L"File Type Label:"
#define FWVIZ_DEF_FILE_EOL_LABEL    L"File Records Terminator:"
#define FWVIZ_DEF_MCBS_CHECKBOX     L"Multi-byte Character Data"
#define FWVIZ_DEF_ADFT_GROUP_LABEL  L"Auto-Detect File Type"
#define FWVIZ_DEF_ADFT_LINE_LABEL   L"Line No:"
#define FWVIZ_DEF_ADFT_REGEX_LABEL  L"Line Regex:"
#define FWVIZ_DEF_FILE_THEME_LABEL  L"File Color Theme:"
#define FWVIZ_DEF_FILE_ACCEPT_BTN   L"Accept"
#define FWVIZ_DEF_FILE_NEW_BTN      L"New"
#define FWVIZ_DEF_FILE_CLONE_BTN    L"Clone"
#define FWVIZ_DEF_FILE_DEL_BTN      L"Delete"
#define FWVIZ_DEF_REC_GROUP_BOX     L"Record Types"
#define FWVIZ_DEF_REC_MOVE_DOWN     L"Move down the selected Record Type"
#define FWVIZ_DEF_REC_MOVE_UP       L"Move up the selected Record Type"
#define FWVIZ_DEF_REC_DESC_LABEL    L"Record Type Label:"
#define FWVIZ_DEF_REC_START_LABEL   L"Record Starts With:"
#define FWVIZ_DEF_REC_REGEX_LABEL   L"Record Regex Key:"
#define FWVIZ_DEF_REC_THEME_LABEL   L"Record Color Theme:"
#define FWVIZ_DEF_REC_THEME_FROM_FT L"[Use FileType Theme]"
#define FWVIZ_DEF_REC_ACCEPT_BTN    L"Accept"
#define FWVIZ_DEF_REC_NEW_BTN       L"New"
#define FWVIZ_DEF_REC_CLONE_BTN     L"Clone"
#define FWVIZ_DEF_REC_DEL_BTN       L"Delete"
#define FWVIZ_DEF_FIELD_GROUP_BOX   L"Fields"
#define FWVIZ_DEF_FIELD_WIDTHS_TEXT L"Widths:"
#define FWVIZ_DEF_FIELD_LABELS_TEXT L"Labels:"
#define FWVIZ_DEF_FIELD_ACCEPT_BTN  L"Accept"
#define FWVIZ_DEF_FIELD_RESET_BTN   L"Reset"
#define FWVIZ_DIALOG_SAVE_BTN       L"&Save as Primary Configuration"
#define FWVIZ_DIALOG_RESET_BTN      L"&Reload Primary Configuration"
#define FWVIZ_DIALOG_BKUP_LOAD_BTN  L"&Load Backup Configuration"
#define FWVIZ_DIALOG_BKUP_VIEW_BTN  L"&View Backup Folder"
#define FWVIZ_DIALOG_EXTRACT_BTN    L"E&xtract Selected File Type Data"
#define FWVIZ_DIALOG_APPEND_BTN     L"&Append New File Type Data"
#define FWVIZ_DIALOG_CLOSE_BTN      L"&Close"

#define FWVIZ_DIALOG_ANSI_TITLE     L"ANSI characters only!"
#define FWVIZ_DIALOG_ANSI_MESSAGE   L"This edit field will only accept ANSI characters."
#define FWVIZ_DIALOG_NUMERIC_TITLE  L"Numbers only!"
#define FWVIZ_DIALOG_NUMERIC_MSG    L"This edit field will only accept numbers,\r\nwith an optional leading minus sign."
#define FWVIZ_DIALOG_COMMAS_TITLE   L"Commas are item separators"
#define FWVIZ_DIALOG_COMMAS_MESSAGE L"The line will be split into multiple items when the 'Accept' button below is clicked."
#define FWVIZ_DISCARD_CHANGES       L"Discard changes?"
#define FWVIZ_OPEN_BKUP_CONFIG_DLG  L"Open Backup Configuration File"
#define FWVIZ_SAVE_BKUP_CONFIG_DLG  L"Save Backup Configuration File"
#define FWVIZ_FT_NEW_ACTION         L"Add New File Type"
#define FWVIZ_FT_CLONE_ACTION       L"Clone Selected File Type"
#define FWVIZ_FT_APPEND_ACTION      L"Append File Type(s)"
#define FWVIZ_FT_LIMIT_ERROR        L"Only %i File Types can be defined."
#define FWVIZ_RT_NEW_ACTION         L"Add New Record Types"
#define FWVIZ_RT_CLONE_ACTION       L"Clone Selected Record Types"
#define FWVIZ_RT_LIMIT_ERROR        L"Only %i Record Types can be defined per File Type."
#define FWVIZ_DEF_MCBS_HINT_TITLE   L"Multi-byte Character Data"
#define FWVIZ_DEF_MCBS_HINT_TEXT    L"1. Check this box only if the file type is likely to contain multi-byte character data.\r\n\r\n2. When this box is checked, field widths will be calculated using character counts. And, TABs will be counted as multiple spaces (or characters).\r\n\r\n3. When this box is unchecked, field widths will be calculated using byte counts.\r\n\r\nClick the (i) icon to view the online documentation."
#define FWVIZ_DEF_ADFT_HINT_TITLE   L"ADFT in a Nutshell"
#define FWVIZ_DEF_ADFT_HINT_TEXT    L"1. Line Numbers begin at '1', counting forwards from the start of file. Negative line numbers will count backwards from the end of file. Zero and numbers (+ve or -ve) beyond file line count will fail ADFT matching.\r\n\r\n2. ADFT Regexes with no terminating '$' will be used as *starts-with* match. Whereas, those with terminating '$' will be used as *full-line* match. ADFT Regexes will have an implicit caret(^) at the start if it has not been explicitly included.\r\n\r\nClick the (i) icon to view the online ADFT documentation."
#define FWVIZ_DEF_RECTHEME_HINT_HDR L"Record-type Theme"
#define FWVIZ_DEF_RECTHEME_HINT_TXT L"Specify a different color theme than the file-type theme for select-few record types to make them distinctive.\r\n\r\nFor an example, see: 'Transaction Headers' inside the Samples » Treasury IPAC file.\r\n\r\nClick the (i) icon to view the online documentation."


// Theme Dialog
#define THEME_DIALOG_TITLE          L"Visualizer Theme Editor"
#define THEME_DEF_GROUP_BOX         L"Themes"
#define THEME_DEF_MOVE_DOWN         L"Move down the selected Theme"
#define THEME_DEF_MOVE_UP           L"Move up the selected Theme"
#define THEME_DEF_DESC_LABEL        L"Theme Label:"
#define THEME_DEF_ACCEPT_BTN        L"Accept"
#define THEME_DEF_NEW_BTN           L"New"
#define THEME_DEF_CLONE_BTN         L"Clone"
#define THEME_DEF_DEL_BTN           L"Delete"
#define THEME_STYLE_GROUP_BOX       L"Styles"
#define THEME_STYLE_MOVE_DOWN       L"Move down the selected Style"
#define THEME_STYLE_MOVE_UP         L"Move up the selected Style"
#define THEME_STYLE_CLONE_BTN       L"Clone"
#define THEME_STYLE_NEW_BTN         L"New"
#define THEME_STYLE_DEL_BTN         L"Delete"
#define THEME_STYLE_DEF_GROUP_BOX   L"Style Definition"
#define THEME_STYLE_DEF_BACKCOLOR   L"Back Color:"
#define THEME_STYLE_DEF_FORECOLOR   L"Fore Color:"
#define THEME_STYLE_DEF_BOLD        L"Bold"
#define THEME_STYLE_DEF_ITALICS     L"Italics"
#define THEME_STYLE_DEF_OUT_LABEL   L"Output:"
#define THEME_STYLE_DEF_OUTPUT      L"SPHINX OF BLACK QUARTZ,\r\nJUDGE MY VOW.\r\n9876543210"
#define THEME_STYLE_DEF_ACCEPT_BTN  L"Accept"
#define THEME_STYLE_DEF_RESET_BTN   L"Reset"
#define THEME_DIALOG_SAVE_BTN       L"&Save as Primary Themes File"
#define THEME_DIALOG_RESET_BTN      L"&Reload Primary Themes File"
#define THEME_DIALOG_BKUP_LOAD_BTN  L"&Load Backup Themes File"
#define THEME_DIALOG_BKUP_VIEW_BTN  L"&View Backup Folder"
#define THEME_DIALOG_EXTRACT_BTN    L"E&xtract Selected Theme Data"
#define THEME_DIALOG_APPEND_BTN     L"&Append New Theme Data"
#define THEME_DIALOG_CLOSE_BTN      L"&Close"

#define THEME_DIALOG_HEX_TITLE      L"Hexadecimal characters only!"
#define THEME_DIALOG_HEX_CHARS_ONLY L"This edit field will only accept characters in the following range: 0-9|A-F|a-f"
#define THEME_DEF_NEW_ACTION        L"Add New Theme"
#define THEME_DEF_CLONE_ACTION      L"Clone Selected Theme"
#define THEME_DEF_APPEND_ACTION     L"Append Theme(s)"
#define THEME_DEF_LIMIT_ERROR       L"Only %i Themes can be defined."
#define THEME_STYLE_NEW_ACTION      L"Add New Style"
#define THEME_STYLE_CLONE_ACTION    L"Clone Selected Style"
#define THEME_STYLE_LIMIT_ERROR     L"Only %i Styles can be defined per Theme."

#define THEME_DISCARD_CHANGES       L"Discard changes?"
#define THEME_OPEN_BKUP_CONFIG_DLG  L"Open Backup Themes File"
#define THEME_SAVE_BKUP_CONFIG_DLG  L"Save Backup Themes File"


// Exim File Type Dialog
#define FT_EXIM_EXTRACT_FT_TITLE    L"Extract File Type Metadata"
#define FT_EXIM_APPEND_FT_TITLE     L"Append File Type Metadata"
#define FT_EXIM_EDIT_FT_LABEL       L"File Type Metadata:"
#define FT_EXIM_EXTRACT_THEME_TITLE L"Extract Visualizer Theme Data"
#define FT_EXIM_APPEND_THEME_TITLE  L"Append Visualizer Theme Data"
#define FT_EXIM_EDIT_THEME_LABEL    L"Visualizer Theme Data:"
#define FT_EXIM_LOAD_FILE_BTN       L"&Load from a File"
#define FT_EXIM_SAVE_FILE_BTN       L"&Save to a File"
#define FT_EXIM_APPEND_BTN          L"&Append File Type"
#define FT_EXIM_CLOSE_BTN           L"&Close"


// Jump Field Dialog
#define JUMP_FIELD_DIALOG_TITLE     L"Jump to Field"
#define JUMP_FIELD_SELECT_LABEL     L"&Select Field:"
#define JUMP_FIELD_GO_BTN           L"&Jump"
#define JUMP_FIELD_CLOSE_BTN        L"&Cancel"
#define JUMP_LABEL_CARET_FLASH      L"Cursor Flash duration (in seconds)"
#define JUMP_TIP_CARET_FLASH        L"When the cursor is set at its default width of '1', it can be hard to spot the cursor at its new position. To aid quick spotting, the cursor is briefly set to block mode at the destination position.\r\n\r\nSpecify the number of seconds to have the cursor flashing in block mode at the destination position."


// Data Extraction Dialog
#define DATA_EXTRACT_DIALOG_TITLE   L"Fixed-Width Data Extraction"
#define DATA_EXTRACT_PREFIX_LABEL   L"Prefix Text¹"
#define DATA_EXTRACT_RECORD_LABEL   L"Record Type"
#define DATA_EXTRACT_FIELD_LABEL    L"Field"
#define DATA_EXTRACT_SUFFIX_LABEL   L"Suffix Text¹"
#define DATA_EXTRACT_ADD_LINE_ITEM  L"Insert Line Item\t[CTRL+Insert]"
#define DATA_EXTRACT_DEL_LINE_ITEM  L"Delete Line Item\t[CTRL+Delete]"
#define DATA_EXTRACT_PAGE_PREV      L"Previous Page\t[CTRL+Page Up]"
#define DATA_EXTRACT_PAGE_NEXT      L"Next Page\t[CTRL+Page Down]"
#define DATA_EXTRACT_PAGE_ADD       L"Add Page\t[CTRL+SHIFT+Insert]"
#define DATA_EXTRACT_PAGE_DEL       L"Delete Page\t[CTRL+SHIFT+Delete]"
#define DATA_EXTRACT_MOVE_DOWN      L"Move down the selected Line Item\t[CTRL+Down Arrow]"
#define DATA_EXTRACT_MOVE_UP        L"Move up the selected Line Item\t[CTRL+Up Arrow]"
#define DATA_EXTRACT_EXTRACT_BTN    L"E&xtract Data"
#define DATA_EXTRACT_CLOSE_BTN      L"&Close"
#define DATA_EXTRACT_TEMPLATE_GROUP L"Reusable Templates"
#define DATA_EXTRACT_TEMPLATE_CURR  L"Show only current FileType Templates"
#define DATA_EXTRACT_TEMPLATE_OTHER "[Other] "
#define DATA_EXTRACT_TEMPLATE_LOAD  L"Load Template:"
#define DATA_EXTRACT_TEMPLATE_NAME  L"Template Name:"
#define DATA_EXTRACT_TEMPLATE_SAVE  L"&Save Template"
#define DATA_EXTRACT_TEMPLATE_NEW   L"&New"
#define DATA_EXTRACT_TEMPLATE_DEL   L"&Delete"
#define DATA_EXTRACT_NEW_LINE_TAB   L"Tip¹:\nIn Prefix and Suffix Text boxes,\nuse \\n for New Lines and \\t for TABs."
#define DATA_EXTRACT_KEYBOARD_TIP   L"Easy Keyboard Shortcuts"
#define DATA_EXTRACT_DELETE_PROMPT  L"Delete Template?"
#define DATA_EXTRACT_INVTEMPL_TITLE L"Invalid Template Name!"
#define DATA_EXTRACT_INVTEMPL_MSG   L"\"[\" and \"]\" are disallowed in Template Name."
#define DATA_EXTRACT_CHANGED_DOC    L"The currently active document is of a different File Type.\r\n\r\nUnable to proceed with data extraction."


// Info Button Links
#define VIZPANEL_INFO_README        L"https://github.com/shriprem/FWDataViz/blob/master/README.md"
#define FWVIZ_DEF_INFO_README       L"https://github.com/shriprem/FWDataViz/blob/master/docs/file_type_config_dialog.md"
#define FWVIZ_DEF_MCBS_INFO_README  L"https://github.com/shriprem/FWDataViz/blob/master/docs/multibyte_character_data.md"
#define FWVIZ_DEF_ADFT_INFO_README  L"https://github.com/shriprem/FWDataViz/blob/master/docs/auto_detect_file_type.md"
#define FWVIZ_RT_THEME_INFO_README  L"https://github.com/shriprem/FWDataViz/blob/master/docs/record_type_theme.md"
#define THEME_DEF_INFO_README       L"https://github.com/shriprem/FWDataViz/blob/master/docs/theme_config_dialog.md"
#define FILE_EXTRACT_INFO_README    L"https://github.com/shriprem/FWDataViz/blob/master/docs/file_type_extract_dialog.md"
#define FILE_APPEND_INFO_README     L"https://github.com/shriprem/FWDataViz/blob/master/docs/file_type_append_dialog.md"
#define THEME_EXTRACT_INFO_README   L"https://github.com/shriprem/FWDataViz/blob/master/docs/theme_extract_dialog.md"
#define THEME_APPEND_INFO_README    L"https://github.com/shriprem/FWDataViz/blob/master/docs/theme_append_dialog.md"
#define DATA_EXTRACT_INFO_README    L"https://github.com/shriprem/FWDataViz/blob/master/docs/data_extract_dialog.md"
#define DATA_EXTRACT_KEYNAV_README  L"https://github.com/shriprem/FWDataViz/blob/master/docs/data_extract_key_shortcuts.md"
