#pragma once

// Common
#define MENU_PANEL_NAME             L"Fixed-Width Data Visualizer"
#define MENU_SHOW_PANEL             L"&Show Panel"
#define MENU_CARET_FRAMED           L"Framed Current Line"
#define MENU_CONFIG                 L"&Configure File Types"
#define MENU_DEMO_SINGLE_REC_FILES  L"Sample Single-Record-Type Files"
#define MENU_DEMO_MULTI_REC_FILES   L"Sample Multiple-Record-Type Files"
#define MENU_DEMO_MULTI_LINE_FILES  L"Sample Multiple-Line Record Files"
#define MENU_ABOUT                  L"&About"


// Fixed Width Data Visualizer Panel
#define VIZ_PANEL_FILETYPE_LABEL    L"&File Type:"
#define VIZ_PANEL_THEME_LABEL       L"&Visualizer Theme:"
#define VIZ_PANEL_CLEAR_BUTTON      L"&Clear"
#define VIZ_PANEL_CLOSE             L"C&lose"
#define VIZ_PANEL_FIELD_LABEL       L"Cursor Position Data"
#define VIZ_PANEL_FILE_CONFIG_TIP   L"Open FileType Metadata Editor"
#define VIZ_PANEL_THEME_CONFIG_TIP  L"Open Visualizer Theme Editor"
#define VIZ_PANEL_WORDWRAP_INFO     L"Visualizer is impaired when wordwrap is enabled."
#define VIZ_PANEL_CARET_FRAMED      L"Framed Current Line"
#define VIZ_PANEL_WORDWRAP_BUTTON   L"Turnoff Wordwrap"


// About Dialog
#define ABOUT_DIALOG_TITLE          L"About"
#define ABOUT_PLUGIN_NAME           L"Fixed Width Data Visualizer Plugin for Notepad++"
#define ABOUT_BTN_LABEL_OK          L"&OK"

// Configuration Dialog
#define FWVIZ_DIALOG_TITLE          L"Fixed Width File Metadata Editor"
#define FWVIZ_DEF_FILE_GROUP_BOX    L"File Types"
#define FWVIZ_DEF_FILE_MOVE_DOWN    L"Move down the selected File Type"
#define FWVIZ_DEF_FILE_MOVE_UP      L"Move up the selected File Type"
#define FWVIZ_DEF_FILE_DESC_LABEL   L"File Type Label:"
#define FWVIZ_DEF_FILE_EOL_LABEL    L"File Records Terminator:"
#define FWVIZ_DEF_FILE_THEME_LABEL  L"File Color Theme:"
#define FWVIZ_DEF_FILE_NEW_BTN      L"New"
#define FWVIZ_DEF_FILE_ACCEPT_BTN   L"Accept"
#define FWVIZ_DEF_FILE_DEL_BTN      L"Delete"
#define FWVIZ_DEF_REC_GROUP_BOX     L"Record Types"
#define FWVIZ_DEF_REC_MOVE_DOWN     L"Move down the selected Record Type"
#define FWVIZ_DEF_REC_MOVE_UP       L"Move up the selected Record Type"
#define FWVIZ_DEF_REC_DESC_LABEL    L"Record Type Label:"
#define FWVIZ_DEF_REC_START_LABEL   L"Record Starts With:"
#define FWVIZ_DEF_REC_REGEX_LABEL   L"Record Regex Key:"
#define FWVIZ_DEF_REC_NEW_BTN       L"New"
#define FWVIZ_DEF_REC_ACCEPT_BTN    L"Accept"
#define FWVIZ_DEF_REC_DEL_BTN       L"Delete"
#define FWVIZ_DEF_FIELD_GROUP_BOX   L"Fields:"
#define FWVIZ_DEF_FIELD_WIDTHS_TEXT L"Widths:"
#define FWVIZ_DEF_FIELD_LABELS_TEXT L"Labels:"
#define FWVIZ_DEF_FIELD_ACCEPT_BTN  L"Accept"
#define FWVIZ_DIALOG_SAVE_BTN       L"&Save as Primary Configuration"
#define FWVIZ_DIALOG_RESET_BTN      L"&Reload Primary Configuration"
#define FWVIZ_DIALOG_BKUP_LOAD_BTN  L"&Load Backup Configuration"
#define FWVIZ_DIALOG_BKUP_VIEW_BTN  L"&View Backup Folder"
#define FWVIZ_DIALOG_CLONE_BTN      L"&Clone Selected File Type Data"
#define FWVIZ_DIALOG_EXTRACT_BTN    L"E&xtract Selected File Type Data"
#define FWVIZ_DIALOG_APPEND_BTN     L"&Append New File Type Data"
#define FWVIZ_DIALOG_CLOSE_BTN      L"Clos&e"

#define FWVIZ_DIALOG_ANSI_TITLE     L"ANSI characters only!"
#define FWVIZ_DIALOG_ANSI_MESSAGE   L"This edit field will only accept ANSI characters."
#define FWVIZ_DIALOG_COMMAS_TITLE   L"Commas are item separators"
#define FWVIZ_DIALOG_COMMAS_MESSAGE L"The line will be split into multiple items when the 'Accept' button below is clicked."
#define FWVIZ_DISCARD_CHANGES       L"Discard changes?"
#define FWVIZ_OPEN_BKUP_CONFIG_DLG  L"Open Backup Configuration File"
#define FWVIZ_SAVE_BKUP_CONFIG_DLG  L"Save Backup Configuration File"

// Exim File Type Dialog
#define FT_EXIM_EXTRACT_DLG_TITLE   L"Extract File Type Data"
#define FT_EXIM_APPEND_DLG_TITLE    L"Append File Type Data"
#define FT_EXIM_EDIT_LABEL          L"File Type Metadata:"
#define FT_EXIM_LOAD_FILE_BTN       L"&Load from a File"
#define FT_EXIM_SAVE_FILE_BTN       L"&Save to a File"
#define FT_EXIM_APPEND_BTN          L"&Append File Type"
#define FT_EXIM_CLOSE_BTN           L"&Close"
