@ECHO OFF

SET PLUGIN_NAME=FWDataViz
SET BIN_DIR=bin64\
SET NOTEPAD_DIR=C:\Portable\Notepad++\
SET PLUGINS_DIR=%NOTEPAD_DIR%\plugins\%PLUGIN_NAME%\

COPY LICENSE %BIN_DIR%
COPY %BIN_DIR%\%PLUGIN_NAME%.dll "%PLUGINS_DIR%"

START /D "%NOTEPAD_DIR%" notepa~1.exe
EXIT 0
